
<br /><br /> 

<div style="padding: 25px;" dir="rtl">
    <?php
    echo '<form enctype="multipart/form-data" method=post  action=' . $this->baseUrl() . '/category/addcategory role=form>';
    echo $this->addCatForm->name;
    echo $this->addCatForm->desc;
    ?>
   <strong> صورة للتصنيف : </strong><input name="cat_img" type="file" />
    <?php
    echo $this->addCatForm->اضف;
    echo '</form>';
    ?> 
</div>



