<br><br><br>

<form action="\html_lab\Doc" method="post" >
<fieldset >
<legend DIR="rtl"> <font size="6">تفاصيل الحدث</font></legend>
<h3 dir="rtl"> الاسم </h3>
<?php
    foreach ($this->event as $event) {
?>
<div dir="rtl"><font size='4'><?= $event['name'] ?></font></div>
<br><h3 dir="rtl"> المكان</h3>
<div dir="rtl"><font size='4'><?= $event['location'] ?></font></div>
<br><h3 dir="rtl">الوقت</h3>
<div dir="rtl"><font size='4'><?= $event['date'] ?></font></div>
<br><h3 dir="rtl">معلومات</h3>
<div dir="rtl"><font size='4'><?= $event['description'] ?></font></div>

<?php
    }
?>

</fieldset>

</form>